# used to install all databases in containers

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    command: "-c logging_collector=on -c log_directory='/var/log/postgresql' -c log_filename='postgresql-%Y-%m-%d_%H%M%S.log' -c log_statement='all'"
    environment:
      POSTGRES_USER: user #TODO: move to env
      POSTGRES_PASSWORD: password #TODO: move to env
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - ./db_data/pq_data:/var/lib/postgresql/data/:z #999:999
      - ./db_data/pq_logs:/var/log/postgresql:z #999:999
    restart: always


  redis:
    image: redis:latest
    container_name: redis-db
    ports:
      - "6379:6379"
    networks:
      - my-network
    volumes:
      - ./db_data/r_data:/data:z #999:999
      - ./db_data/r_logs:/log/:z #999:999
      - ./db_default/redis:/default_config:z
    command: redis-server /default_config/redis.conf 
    restart: always


  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    networks:
      - my-network
    volumes:
      - ./db_data/m_data:/data/db:z #999:999
      - ./db_data/m_logs:/var/log/mongodb:z  #999:999
    command: 
    - '--logpath'
    - '/var/log/mongodb/mongod.log'
    - '--logappend'
    - '--bind_ip_all'
    restart: always

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-db
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "Opensearch1_" 
      cluster.name: opensearch-cluster
      node.name: opensearch-db
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - my-network
    # volumes:
    #   - ./db_data/os_logs:/usr/share/opensearch/logs:z #999:999
    #   - ./db_data/os_data:/usr/share/opensearch/data:z #999:999
    restart: always

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.17.0 
    container_name: opensearch-dashboards
    ports:
      - 5601:5601 
    expose:
      - "5601" 
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]' 
    networks:
      - my-network

  neo4j:
    image: neo4j:latest
    container_name: neo4j-db
    environment:
      NEO4J_AUTH: neo4j/password  
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    networks:
      - my-network
    volumes:
      - ./db_data/nj_data:/var/lib/neo4j/data #7474:7474
      - ./db_data/nj_logs:/var/lib/neo4j/logs #7474:7474
    restart: always


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: iqumalwer@google.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8080:80"
    networks:
      - my-network
    restart: always


networks:
  my-network:
    driver: bridge



